fix(llmisvc): compatibility with podman for container builds
This adds compatibility to build the llmisvc-controller with podman:
* Podman does not have the `--push` flag for `build` command. Thus, use the `push` commmand.
* In the dockerfile, use `USER root` for the build stage. Otherwise, the following error is
  emitted:

```
[1/2] STEP 8/12: RUN CGO_ENABLED=0 GOOS=linux go build -a -o manager ./cmd/llmisvc
github.com/kserve/kserve/cmd/llmisvc: go build github.com/kserve/kserve/cmd/llmisvc: copying /tmp/go-build1108754253/b001/exe/a.out: open manager: permission denied
Error: building at STEP "RUN CGO_ENABLED=0 GOOS=linux go build -a -o manager ./cmd/llmisvc": while running runtime: exit status 1
```

Signed-off-by: Edgar Hernández <23639005+israel-hdez@users.noreply.github.com>